# Utilisez une image de base avec Python préinstallé
FROM python:3.11-slim

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le fichier des dépendances (requirements.txt) dans le conteneur
COPY requirements.txt .

# Installez les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copiez le reste du code dans le conteneur
COPY . .

# Exposez le port que votre application utilise
EXPOSE 5000

# Commande à exécuter lorsque le conteneur démarre
#CMD ["python", "backend_flask.py"]

CMD ["./start.sh"]

